emp_code = int(input("Enter Employee Code : "))
emp_name = input("Enter Employee Full Name : ")
emp_age = int(input("Enter Age : "))
emp_email = input("Enter Email Address : ")
emp_phone = input("Enter Mobile Number : ")

print("Emp_Code : ",emp_code)
print("Emp Name : ",emp_name)
print("Emp Age : ",emp_age)
print("Emp Email Address : ",emp_email)
print("Emp Mobile Number : ",emp_phone)